<form action="/index" method="post">

	<p>
		<label>region</label>
		<select name="region" id="regionlist">
		<?php
		foreach ($this->regions as $rname) {
			$selected = ($this->detected_region == $rid) ? ' selected="selected"' : '';
		?>
		<option value="<?php echo $rname; ?>"<?php echo $selected; ?>><?php echo $rname; ?></option>
		<?php } ?>
		</select>
	</p>

	<p>
		<label>realm</label>
		<input type="text" name="realm_name" id="realm_name" autocomplete="off" />
		<span class="ajaxload" id="realm_name_loading" style="display: none;"></span>
		<ul id="realm_suggest"></ul>
	</p>

	<p>
		<label>character name</label>
		<input type="text" name="char_name" id="char_name" />
	</p>

	<p>
		<input type="submit" value="go" />
	</p>
</form>

<script type="text/javascript">
$(document).ready(function() {
	Funcs.initRealmLookup();
});
</script>