<div id="char_lookup" class="dark_panel">
	<form action="/index" method="post" autocomplete="off">
	
		<h1>Character Search</h1>

		<div class="region">
			<label></label>
			<select id="regionlist" class="prefill" name="region">
				<option value="">region</option>
			<?php
			foreach ($this->regions as $rid=>$rname) {
				$selected = ($this->detected_region == $rid) ? ' selected="selected"' : '';
			?>
			<option value="<?php echo $rname; ?>"<?php echo $selected; ?>><?php echo $rname; ?></option>
			<?php } ?>
			</select>
		</div>

		<div class="realm">
			<label></label>
			<input type="text" class="prefill" name="realm_name" id="realm_name" value="realm" />
			<span id="realm_name_status"></span>
			<ul id="realm_suggest"></ul>
		</div>

		<div class="character">
			<label></label>
			<input type="text" class="prefill" name="char_name" id="char_name" value="character" />
		</div>

		<input class="submit" type="submit" value="" />
	</form>
</div>
<p id="lookup_error"></p>

<script type="text/javascript">
$(document).ready(function() {
	Funcs.initCharLookup();
});
</script>