<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
		<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />

		<link href='http://fonts.googleapis.com/css?family=Gudea:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
		<link type="text/css" rel="stylesheet" href="/css/screen.css" />
		<link type="text/css" rel="stylesheet" href="/css/admin.css" />
	</head>

	<body>
		<div id="frame">
			<ul id="admin_menu">
				<li><a href="/admin/">Home</a></li>
				<li><a href="/admin/sync-realms">Sync Realms</a></li>
				<li><a href="/admin/sync-achievements">Sync Achievements</a></li>

			</ul>
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>