<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
		<script type="text/javascript" src="/js/funcs.js"></script>
		<script type="text/javascript" src="/js/app.js"></script>
		<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />

		<link href='http://fonts.googleapis.com/css?family=Gudea:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
		<link type="text/css" rel="stylesheet" href="/css/screen.css" />

		<?php echo $this->headTitle(); ?>
	</head>

	<body>
		<div id="logo_bar"></div>
		<div id="frame">
			<div id="header">
				<a id="logo" href="/"></a>
			</div>
			<?php echo $this->layout()->content; ?>
		</div>

		<div id="footer" class="panel">
			Copyright <?php echo date("Y"); ?> WoW Timeline
			<span style="float: right;">World of Warcraft copyright <a href="http://www.blizzard.com" target="_blank">Blizzard Entertainment</a></span>
		</div>
		<script type="text/javascript">
		$(document).ready(function() {
			Funcs.init();
		});

		<?php
		if (APPLICATION_ENV == 'production') {
		?>
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-31179122-1']);
		_gaq.push(['_trackPageview']);

		(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

		<?php
		}
		?>
		</script>
	</body>
</html>