<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
		<script type="text/javascript" src="/js/funcs.js"></script>
		<script type="text/javascript" src="/js/app.js"></script>
		<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link rel="image_src" href="/images/share_icon.png" />

		<link href='http://fonts.googleapis.com/css?family=Gudea:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css' />
		<link type="text/css" rel="stylesheet" href="/css/screen.css?v=2" />
		<link rel="shortcut icon" href="/favicon.ico" />

		<?php echo $this->headTitle(); ?>
		<meta name="keywords" content="wow, world of warcraft, timeline, character, char, achievements" />
		<meta name="description" content="Look back at your World of Warcraft character's achievements" />
	</head>

	<body>
		<div id="logo_bar"></div>
		<div id="frame">
			<div id="header">
				<a id="logo" href="/" title="WoW Timeline"></a>
				<a id="beta" title="If you spot any bugs, please let me know :-)">BETA</a>
				<ul id="mainmenu">
					<li><a href="/">Home</a></li>
					<li><a href="/feedback">Feedback</a></li>
				</ul>
                <div class="fb-like" data-href="http://wowtimeline.net/" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-colorscheme="dark" data-layout="standard" data-action="like" data-show-faces="true" data-send="false"></div>
			</div>
			<?php echo $this->layout()->content; ?>
		</div>

		<div id="footer" class="panel">
            <a class="ninja" href="http://cloakedninjas.co.uk" target="_blank"></a>
            &copy; <?php echo date("Y"); ?>
			<span style="float: right;">World of Warcraft copyright <a href="http://www.blizzard.com" target="_blank">Blizzard Entertainment</a></span>
		</div>
		<script type="text/javascript">
		$(document).ready(function() {
			Funcs.init();
		});

		<?php
		if (APPLICATION_ENV == 'production') {
		?>
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-31179122-1']);
		_gaq.push(['_trackPageview']);

		(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

		<?php
		}
		?>
		</script>
        <div id="fb-root"></div>
        <script>
        (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        </script>
	</body>
</html>
