<?php
if ($this->error !== null) {
?>
<div class="error_msg">
	<h1>Uh oh, something has gone wrong :(</h1>
	<p><?php echo $this->error; ?>
</div>
<?php
}
else {
?>

<script type="text/javascript">
Timeline.data = <?php echo $this->json_data; ?>;
Timeline.total_achvs = <?php echo count($this->char->achievements); ?>;
Timeline.total_points = <?php echo $this->char->achievement_points; ?>;
Timeline.total_entries = <?php echo $this->char->total_entries; ?>;

$(document).ready(function() {
	Timeline.init();
});
</script>

<div id="char_header">

	<div class="profile">
		<div class="thumb" style="background-image: url(<?php echo $this->char->getThumbnail(); ?>)"></div>

		<h1><?php echo sprintf($this->char->title, $this->char->name); ?></h1>
		<h2>&lt; <?php echo $this->char->guildName; ?> &gt;</h2>
		<h3>
			<span class="level"><?php echo $this->char->level; ?></span><span class="race"><?php echo $this->char->getRacialName(); ?></span><span class="class c<?php echo $this->char->class; ?>"><?php echo $this->char->getClassName(); ?></span>
		</h3>
	</div>
</div>

<div id="timeline">
	<div id="time_index">
		<div id="exp_2" class="exp cata"></div>
		<div id="exp_1" class="exp wotlk"></div>
		<div id="exp_0" class="exp tbc"></div>
	</div>
	<div class="entries"></div>

	<div class="loading">Loading...</div>
</div>

<div id="entry_template" class="entry">
	<span class="date"></span>
	<span class="l"></span>
</div>

<div id="notable_template" class="entry notable">
	<span class="date"></span>
</div>
<?php
}
?>